[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kinopy"
version = "1.0"
dependencies = [
    "backports.strenum ; python_version < '3.11'",
    "requests",
    "lxml",
]
