[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kinopy"
version = "1.0"
requires-python = ">=3.9"
dependencies = [
    "backports.strenum ; python_version < '3.11'",
    "lxml",
    "requests",
    "tomli ; python_version < '3.11'",
]
